### ISSUE TITLE
make syncing script between fs and FC

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/file_catalog#109]
The syncing script should do more than the current indexing script:

1. index new files
2. check timestamp/checksum of existing files. re-index any changed files.
    a. If FC entry has a location not at WIPAC, change logical_name and remove WIPAC location.
3. "remove" location of files that have been deleted/overwritten
	a. "remove" could mean outright deleting the entry, or adding a flag to the entry

**Comment by ric-evans** [comment]
Note: This would be ran manually, ad-hoc, immediately after a known bulk removal is made.

**Comment by ric-evans** [comment]
An issue with deleting a location is that the `logical_name` would already exist for a re-written/restored file.

A solution would be to no longer enforce unique `logical_name`s, and add logic to handle this scenario in the Indexing script / FC REST interface. Currently, you cannot add a record with the same `logical_name`, unless you PATCH (in which case you would lose the previous metadata).

**Comment by ric-evans** [comment]
### Solution I: Non-Unique `logical_name`
A solution would be to no longer enforce unique `logical_name`s, and add logic to handle this scenario in the Indexing script / FC REST interface. Currently, you cannot add a record with the same `logical_name`. You can PATCH, but you would lose the previous metadata... not good.
- Example Future Scenario:
  + I want the FC record at `/my/data/warehouse/path/to/file`
  + So, I call `/api/files` with query, `{'logical_name':'/my/data/warehouse/path/to/file'}`
  + FC returns two files with `logical_name` = `/my/data/warehouse/path/to/file`
  + Do I use record A or record B? 
     - My existing script probably assumes there's only one matching file here (`my_file = ret[0]`)

**Comment by ric-evans** [comment]
### Solution II: Prepend/Append Metadata to `logical_name`

When a file is removed from lfs (but still exists at NERSC), append `"@nersc"` to the `logcal_name`.
- Example Future Scenario 1:
  + I want the FC record at `/my/data/warehouse/path/to/file`
  + So, I call `/api/files` with query, `{'logical_name':'/my/data/warehouse/path/to/file'}`
  + FC returns **one** file with `logical_name` = `/my/data/warehouse/path/to/file`
  + All is good, I got what I wanted :smile: 
- Example Future Scenario 2:
  + I want all FC records at `/my/data/warehouse/path/to/parent/directory`
  + So, I call `/api/files` with query, `{'directory':'/my/data/warehouse/path/to/parent/directory'}`
  + FC returns **serveral** files, some are only at nersc & some are at least in lfs:
     i. `logical_name` = `/my/data/warehouse/path/to/file1`
     ii. `logical_name` = `/my/data/warehouse/path/to/file1@nersc`
     iii. `logical_name` = `/my/data/warehouse/path/to/file2`
     iv. `logical_name` = `/my/data/warehouse/path/to/file2@nersc`
  + This is would need additional logic, client-side, to filter

**Comment by jnbellinger** [comment]
For Solution 2, we want to make sure we know which version the file is.  The default is version 0, but we could have a situation where NERSC has version 0, DESY version 1, and the warehouse version 3.  (Thank you, reprocessing)  The NERSC/DESY/WIPAC/Malmo location is a different thing.

**Comment by ric-evans** [comment]
### Solution III: No More `logical_name`

This is the base solution from https://github.com/WIPACrepo/file_catalog/issues/79

If **Solution I** and **Solution II**, both require looking at other metadata fields to decide if this is the file(s) I want, then why bother with `logical_name` at all? We can still find the file only using `path`.

- Example Future Scenario 1:
  + I want the FC record at `/my/data/warehouse/path/to/file`
  + So, I call `/api/files` with query, `{'path':'/my/data/warehouse/path/to/file'}`
  + FC returns two records
	A. `locations = [{'path': '/my/data/warehouse/path/to/file', 'site':'WIPAC'}]`
	B. `locations = [{'path': '/my/data/warehouse/path/to/file', 'site':'WIPAC'}, {'path': '/my/data/warehouse/path/to/file', 'site':'NERSC'}]`
  + Do I use record A or record B? 
     - My existing script probably assumes there's only one matching file here (`my_file = ret[0]`)
     - Would need to look at the `create_date` timestamp

**Comment by ric-evans** [comment]
> For Solution 2, we want to make sure we know which version the file is. The default is version 0, but we could have a situation where NERSC has version 0, DESY version 1, and the warehouse version 3. (Thank you, reprocessing) The NERSC/DESY/WIPAC/Malmo location is a different thing.

@jnbellinger What if we moved the `create_date` field to each `location` entry? Can we assume `version 0's create_date` < `version 1's create_date` <`version 2's create_date`

**Comment by jnbellinger** [comment]
A re-index of a file should only overwrite the existing entry if it only exists at WIPAC, otherwise it would generate a new version, and remove the WIPAC aspect of the previous entry.  
Likewise, if a file is deleted and does not exist anywhere but WIPAC, the entry is deleted, otherwise the entry simply has the WIPAC aspect deleted.  Is that about it?

**Comment by jnbellinger** [comment]
We could use the creation date, since that's already there for us, or an integer and avoid date comparisons.  Whichever looks most robust..

**Comment by dsschult** [comment]
> > For Solution 2, we want to make sure we know which version the file is. The default is version 0, but we could have a situation where NERSC has version 0, DESY version 1, and the warehouse version 3. (Thank you, reprocessing) The NERSC/DESY/WIPAC/Malmo location is a different thing.
> 
> @jnbellinger What if we moved the `create_date` field to each `location` entry? Can we assume `version 0's create_date` < `version 1's create_date` <`version 2's create_date`
> 
> For example, a file that has version 0 at MALMO, version 1 at WIPAC+NERSC, and version 2 at DESY:
> A. `locations = [{'path': '/my/data/path/to/file', 'site':'MALMO', 'create_date': Dec-2015}]`
> B. `locations = [{'path': '/my/data/path/to/file', 'site':'WIPAC', 'create_date': Jan-2018}, {'path': '/my/data/path/to/file', 'site':'NERSC', 'create_date: Feb-2018}]`
> C. `locations = [{'path': '/my/data/path/to/file', 'site':'DESY', 'create_date': Jun-2020}]`

Not sure you can use the locations field like this, since the versions would also have different checksums at the very least (and maybe other metadata differences).

**Comment by dsschult** [comment]
Personally, I'm hoping for some minimal solution in this issue that's not full-on versioning, just enough for LTA to function (even if it means adjusting some of the client code with a different query).

**Comment by ric-evans** [comment]
> We could use the creation date, since that's already there for us, or an integer and avoid date comparisons. Whichever looks most robust..

yes, the actual data type would be an integer

**Comment by ric-evans** [comment]
> > > For Solution 2, we want to make sure we know which version the file is. The default is version 0, but we could have a situation where NERSC has version 0, DESY version 1, and the warehouse version 3. (Thank you, reprocessing) The NERSC/DESY/WIPAC/Malmo location is a different thing.
> > 
> > 
> > @jnbellinger What if we moved the `create_date` field to each `location` entry? Can we assume `version 0's create_date` < `version 1's create_date` <`version 2's create_date`
> > For example, a file that has version 0 at MALMO, version 1 at WIPAC+NERSC, and version 2 at DESY:
> > A. `locations = [{'path': '/my/data/path/to/file', 'site':'MALMO', 'create_date': Dec-2015}]`
> > B. `locations = [{'path': '/my/data/path/to/file', 'site':'WIPAC', 'create_date': Jan-2018}, {'path': '/my/data/path/to/file', 'site':'NERSC', 'create_date: Feb-2018}]`
> > C. `locations = [{'path': '/my/data/path/to/file', 'site':'DESY', 'create_date': Jun-2020}]`
> 
> Not sure you can use the locations field like this, since the versions would also have different checksums at the very least (and maybe other metadata differences).

I think there's some confusion on what I meant. I presume you're referring to example record B. All three records here represent three different versions. There's no version-overlapping within a single record. Record B refers to a file that physically exists at WIPAC and NERSC. It was first sent to WIPAC in Jan-2018 and later archived to NERSC in Feb-2018, but it is the same file--the same checksum.

**Comment by ric-evans** [comment]
### Versioning Solution A: Add `write_date` to Location Entries

_This solution is independent of solutions 1, 2, 3..._

Here's a revision of my earlier suggestion. It is "not-quite" versioning. We keep track of the `create_date` (when the file first appeared anywhere, probably Madison) and `write_date` for each location entry. The version can be inferred from the create date. To state the obvious, a _version_ is a file with the same original (Madison) file path but with a different **checksum** and probably different metadata.

For example, a file that has version 0 at MALMO, version 1 at WIPAC+NERSC, and version 2 at DESY:
A. `{..., 'create_date': Jan-2015, 'locations': [{'path': '/my/data/path/to/file', 'site':'MALMO', 'write_date': Dec-2015}], 'checksum':'123abc'}`
B. `{..., 'create_date': Jan-2018, 'locations': [{'path': '/my/data/path/to/file', 'site':'WIPAC', 'write_date': Jan-2018}, {'path': '/my/data/path/to/file', 'site':'NERSC', 'write_date: Feb-2018}], 'checksum':'345def'}`
C. `{..., 'create_date': Jan-2020, 'locations': [{'path': '/my/data/path/to/file', 'site':'DESY', 'write_date': Apr-2020}], 'checksum':'567f0a'}`

**Comment by ric-evans** [comment]
### Summary from the Meeting and TODOs Going Forward

- add `DELETE` path in `api/files` which will smartly delete a location-path OR an entire record, according to a location-path or `logical_name`
	- this will be the heart of the "syncing" script

- make `logical_name` no longer unique
	- settle on a standard for return queried file records, on `GET`
		- return only the newest by default? require a flag to get multiple versions?
		- return all matching files, but descending in version age? `ret[0] = <newest-version>`
	- add check for re-added files with the same `checksum`, aka stop the infinite version scenario
	- update indexer to handle this standard
		- what does the indexer check in order to skip an already-indexed file?
			- `create_date`? not `checksum`! (take too long)
			- is `logical_name` in `location.path`s? aka FC doesn't think this file path has been deleted

**Comment by dsschult** [comment]
For `DELETE`, probably on the `/api/files/([^\/]+)` route.  With an argument for the location to delete.

Is the `create_date` in the file catalog the same as the file create date on disk, or just when it was added to the catalog?

**Comment by jnbellinger** [comment]
I think it would be less confusing to have it be the creation date of the file on disk.

**Comment by dsschult** [comment]
I agree it would be less confusing, but what is it in reality?  (what did the indexing do for files already in the FC?)

**Comment by ric-evans** [comment]
yes, `create_date` is the fs date (`os.path.getctime(self.file.path)`)

**Comment by ric-evans** [comment]
for completeness' sake, there's also the `meta_modify_date` and the `lta.date_archived`

**Comment by ric-evans** [comment]
> For `DELETE`, probably on the `/api/files/([^\/]+)` route. With an argument for the location to delete.

This is the route that requires the uuid, `/api/files/{uuid}`, which does help in pinpointing exactly what path we want.

However, I want to avoid overloading this route. If the payload/body is empty by accident, I wouldn't want to all-out delete the record.

I propose instead we use the underutilized, `/api/files/{uuid}/locations`. This one uses a `locations` list.

@jnbellinger / @blinkdog: does lta use `/api/files/{uuid}/locations` to add its NERSC location?

**Comment by dsschult** [comment]
I have a few issues with this:

1. With `/api/files/{uuid}/locations`, a `DELETE` there would mean deleting all locations.
2. Semantically, REST says if you just want to delete a location, it should be `/api/files/{uuid}/locations/{location_id}`, except we don't have a `location_id` or any other single way of identifying locations.
3. There is also the case of deleting the whole file, which REST says you shouldn't be able to do from such a route.

Of course, a `DELETE` on `/api/files/{uuid}` is supposed to mean a DELETE for the whole file every time, so that's also not perfect REST syntax.

Maybe `POST` `/api/files/{uuid}/actions/remove_location`?  This is using the common actions escape for doing non-REST things, since `POST` can do anything (doesn't have to be idempotent).

----------

The other alternative is that the script itself knows whether it wants to delete the whole record or just the location, and we have `DELETE` methods on both of those routes.

**Comment by ric-evans** [comment]
Sticking with good REST syntax is smart.

Here's an idea:
- add an argument to `/api/files/{uuid}/locations`:`POST` called `remove_locations` (type: list)
	- this will be the same type as the existing `locations` arg
	- this method can do double-duty (add+remove), AKA "move"
- after `/api/files/{uuid}/locations`:`POST` removes the indicated location(s), if there are no more locations, then send back some HTTP Error
	- the FC does not automatically delete the file, just the location entry(ies)
- the client script can except the error, then call `/api/files/{uuid}`:`DELETE`
	- this could allow location-less records, if the client doesn't behave

**Comment by ric-evans** [comment]
alternatively, `/api/files/{uuid}/locations`:`POST` exits early with an HTTP Error, if the arguments would mean deleting all the current locations, without actually removing any locations.

**Comment by dsschult** [comment]
Not sure I like overloading a method like that.  

Currently the `/api/files/{uuid}/locations` `POST` is sticking to proper REST syntax by adding an item to a collection.  Making it do anything else breaks that, and then I'd probably give it a different name.

Reminder on REST syntax: https://restful-api-design.readthedocs.io/en/latest/methods.html

**Comment by blinkdog** [comment]
> I propose instead we use the underutilized, `/api/files/{uuid}/locations`. This one uses a `locations` list.
> 
> @jnbellinger / @blinkdog: does lta use `/api/files/{uuid}/locations` to add its NERSC location?

Yes, I created `/api/files/{uuid}/locations` to cover the LTA use-case of adding a new location for a file (specifically NERSC).

I needed it to create a new location but also de-duplicate; so any reprocessing would not pollute the locations array with duplicate locations.

Adding a duplicate location is not an error; it just returns OK to mean "yep, already got that one" without any changes to the data.

**Comment by blinkdog** [comment]
I'll agree with David that I'd like to avoid overloading write/modify/delete routes with arguments.
Arguments as query parameters in read routes aren't so bad; you get it wrong, you get the wrong stuff back, you fix your query.
Getting it wrong in the write route can be a little bit more of a hassle to fix, depending on how that went.

At the risk of [yak shaving](https://www.hanselman.com/blog/yak-shaving-defined-ill-get-that-done-as-soon-as-i-shave-this-yak), I think the "proper" solution (if we have all the time in the world) is to first have a script add a UUID identifier to each location in each file catalog record, then create the route `DELETE /api/files/{uuid}/locations/{location_uuid}`, while adding ensure-it-has-a-uuid logic to the record creation and location creation routes.

If we don't want to shave that yak, I think these are the best solutions in order of most safe to most dangerous:

1. `POST /api/files/{uuid}/actions/remove_location` (body: location object to be removed)

Pros: Respects data idempotence, keeps the remove logic entirely on the File Catalog server.
Cons: Name isn't pretty or intuitive, and is crafting an "extra" verb because we can't use an orthogonal RESTful one due to lack of IDs.

2. `PATCH /api/files/{uuid}` (body: locations array, with the locations suitably updated)

Pros: RESTful and straightforward; we're PATCHing the record to update the locations.
Cons: Concurrent locations updates are a last-update-wins race condition; this is unlikely in practice (until it isn't).

3. `DELETE /api/files/{uuid}/locations` followed by `POST /api/files/{uuid}/locations`

Pros: ??? Easy to understand?
Cons: Like #2, except your client process can also die after deleting all the locations but before re-adding the ones you want to keep. This is just playing with fire; let's not and say we did.

**Comment by ric-evans** [comment]
@dsschult thanks for the link to the REST methodology, I'd forgotten some of that.

@blinkdog I agree that adding a location uuid is the most RESTful way to go about this. I don't think it's more robust than adding an "action" route--we still get to pinpoint the exact location entry.

I'm in favor of `/api/files/{uuid}/actions/remove_location`:`POST` with a single `location` argument, and requried keys, `site` and `location`.

Sound good?

**Comment by ric-evans** [comment]
About location-less record cleanup: What do we think about automatically deleting the record when a client removes the only location on the record?

A. Automatically and silently remove the record
	- the is quick and easy, but breaks the REST methodology 

B. Only remove the location, make the record location-less, but respond with some indicator that follow-up `DELETE` is needed
	- does exactly what is advertised (removes a location), but this requires the client to behave

C. Don't remove the location, respond with an error, require the client to followup with `DELETE`
	- forces FC data integrity by altering the client's control flow, but doesn't do just what's advertised (remove a location)

All 3 have the potential problem of a race condition where a location is meant to be added after a remove action on the previously solo-location record.

I'm in favor of C.

Thoughts?

**Comment by dsschult** [comment]
If we do `/api/files/{uuid}/actions/remove_location`:`POST` I'm fine with A, as it's not exactly RESTful.

We also have race conditions in other parts of the FC.  I plan on fixing that by changing to Clowder in the future, so A should be "less work" for an acceptable solution now.

**Comment by blinkdog** [comment]
> About location-less record cleanup: What do we think about automatically deleting the record when a client removes the only location on the record?

I think we've decided that we want the File Catalog to be the current catalog of active/accessible files.
In that case, a record without any locations isn't really a record that we want to keep. (~Option B~)

Option A and Option C both work.
It looks like it's a trade-off between simplicity for the client (Option A) and being explicit to avoid surprises (Option C).

[Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) 

So the question boils down to, how surprising is it that removing the last location also removes the record?
Is it worth the risk to get the convenience of writing simple client logic?

This is a judgment call. I think Option A is okay in this instance (given how we define the File Catalog).
Just my opinion though; if we had more people interacting with our API, it would tilt my opinion toward Option C.

**Comment by ric-evans** [comment]
Let's go with A, then. Considering latency over the wire, then this will also be 2x faster for deleting such files.

**Comment by ric-evans** [comment]
I'll do this in 2 PRs:
1. Allow Non-Unique Logical Names
2. Add location-deletion route

**Comment by ric-evans** [comment]
Plus an additional PR for updating the indexer.
