### ISSUE TITLE
Replace `write_error`-`return` with `raise`-`HTTPError` Syntax

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/file_catalog#111]
remembering to return after writing the error is prone to create bugs, especially when the writing is nested in a call stack.

Instead, simply `raise HTTPError`. Some refactoring will be needed for validation/deconfliction methods that return bools.

**Comment by dsschult** [comment]
Example:
```python
raise HTTPError(403, reason="authentication failed")
```
