### ISSUE TITLE
sites and locations

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/file_catalog#21]
Make server return full paths as strings, instead of {'site', 'path'} dict.

Could probably leave the former as a "raw" query method.

Need to handle the type of endpoint desired for the site (http, gridftp, s3, etc).

**Comment by ric-evans** [comment]
@dsschult This functionality is in `logical_name`, though `logical_name` should be immutable. Let's close this issue.

**Comment by ric-evans** [comment]
@blinkdog I just discovered https://github.com/WIPACrepo/file_catalog/blob/5c11477c9d683f436d7ac28f2f1a1ab4a48a1b80/tests/test_files.py#L485 (`test_54_patch_files_uuid_replace_logical_name()`)

Is this still the preferred action? I thought the idea was to make `logical_name` immutable but update the `locations` object as the file moves.

**Comment by dsschult** [comment]
I believe it's checking that you can PATCH with the same logical name, not that you can change it.

Also, the practice of putting the current path in the logical_name is just an artifact of our current filesystem archiving, not something I want to keep forever.

**Comment by dsschult** [comment]
Though we may need to revise this issue, as it was intended to help clients get urls to download from.  That may be a more tricky problem than what was envisioned in 2017.

**Comment by ric-evans** [comment]
Let's spin this off into https://github.com/WIPACrepo/file_catalog/issues/79
