### ISSUE TITLE
New file restrictions

### ISSUE THREAD

**Issue by blinkdog** [WIPACrepo/file_catalog#33]
JIRA: https://wipacit.atlassian.net/browse/DEV-153

AC: Add a new file restriction to check the location, to make sure we don't have overlaps. Has to be handled in the file creation and update handlers. Must be indexed in mongodb.

Also make the logical_name unique.

**Comment by ric-evans** [comment]
@blinkdog can we close this?

PR TLDR: `logical_name` is a unique index, now. Requests will receive a `409` error. Updates can be made via a `PATCH` request.
