### ISSUE TITLE
Cleanup File Catalog Near-Duplicates

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/file_catalog#68]
There are entries in the file catalog with filepaths rooted at `/mnt/lfs*/` which is not good for longevity

**Comment by ric-evans** [comment]
closed by https://github.com/WIPACrepo/file-catalog-indexer/pull/12

**Comment by jnbellinger** [comment]
What do you mean by the "x2"?  Do you mean all 1679  /mnt/lfs7 entries?  The /data/exp entries should be fine

**Comment by ric-evans** [comment]
@jnbellinger responded to you over here: https://github.com/WIPACrepo/file_catalog/issues/98#issuecomment-810641751
