### ISSUE TITLE
Enable Querying by Directory for /api/files

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/file_catalog#77]
Adding a `"directory"` base argument (which would essentially make a `$regex` query on the path-name) would be useful.

This could support the `"logical_name"` path an/or `"locations"` paths.

**Comment by ric-evans** [comment]
This will return files (because `/api/files`), but a similar solution could be used to get sub-directories (`/api/dirs`?). I don't know how useful that would be.

**Comment by dsschult** [comment]
> This will return files (because `/api/files`), but a similar solution could be used to get sub-directories (`/api/dirs`?). I don't know how useful that would be.

My opinion is we shouldn't try to look like a filesystem, because we are not.  Users should mostly rely on metadata queries.

I view the "directory" argument as a helper for our use in retrieving multiple files, not a way to navigate a posix filesystem.
