### ISSUE TITLE
Remedy `mnt`-Rooted FC Entries That Are Also at NERSC

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/file_catalog#98]
(Leftover from https://github.com/WIPACrepo/file_catalog/issues/68)

There are 1679 entries in the FC that are rooted at `/mnt/lfs*/exp` and also duplicated at `/data/exp/`. These files also no longer exist on lfs.

I think we should just delete all 1679x2 FC entries and call it done :smile:

**Comment by dsschult** [comment]
Do either of the entries have NERSC locations?  If so, we need to keep that.

**Comment by ric-evans** [comment]
@jnbellinger By x2 I mean the FC entries rooted at `/mnt/` and those rooted at `/data/`, there are 1679 of each

**Comment by ric-evans** [comment]
@dsschult yes, those rooted at `/mnt/` have NERSC locations. 

But since other entries rooted at `/mnt/` that are no longer in lfs have been deleted from the FC (regardless if they had a NERSC location), I figure deleting these too would be fine. The only difference here is that these 1679 have `/data/`-rooted duplicates.

**Comment by jnbellinger** [comment]
I'm still puzzled.  If we had a file in /data/..., even if we deleted it from the warehouse, so long as it exists in archive we want to keep the info around, right?--just get rid of the duplicate.  Or are there 3 sets of records we're talking about?
Or are  you talking about the dual appearances of PFRawXXX and ukey_HASH_PFRawXXX names for a single file?

**Comment by ric-evans** [comment]
I agree this is getting confusing. I'll run some queries and see if I can clarify things

**Comment by ric-evans** [comment]
I ran queries on each path and now I'm more confused. Regardless, here's the results of the queries:

```
Of the 1679 total paths rooted at /mnt/lfs7/:
- All 1679 are have a NERSC location
- There are 671 with a duplicate rooted at /data/ and those duplicates do not have a NERSC location
- There are 1008 that do not have duplicates
- All 1679 are no longer in lfs/lustre/warehouse
```

And here's my source code for that:

```
In [27]: def has_nersc(file) -> bool: 
    ...:     for loc in file.get('locations',[]): 
    ...:         if loc['site'].upper() == 'NERSC': 
    ...:             return True 
    ...:     return False 
In [28]: import os 
    ...: no_dup = [] 
    ...: has_dup = [] 
    ...: for n in nerscs: 
    ...:     # start w/ the /mnt/-rooted paths 
    ...:     #print(n) 
    ...:     assert not os.path.exists(n) 
    ...:     assert n.startswith('/mnt/lfs7/') 
    ...:     file = rc.request_seq('GET','/api/files',{'path':n, 'all-keys':True})['files'][0] 
    ...:     assert has_nersc(file) 
    ...:  
    ...:     # now try /data/-rooted version 
    ...:     data_rooted = '/data/' + n.strip('/mnt/lfs7/') 
    ...:     #print(data_rooted) 
    ...:     ret = rc.request_seq('GET','/api/files',{'path':data_rooted, 'all-keys':True})['files'] 
    ...:     if ret: 
    ...:         assert not has_nersc(ret[0]) 
    ...:         has_dup.append(n) 
    ...:     else: 
    ...:         no_dup.append(n) 
    ...: print(f'Of the {len(nerscs)} total paths rooted at /mnt/lfs7/:') 
    ...: print(f'- All {len(nerscs)} are have a NERSC location') 
    ...: print(f'- There are {len(has_dup)} with a duplicate rooted at /data/ and those duplicates do not have a NERSC location') 
    ...: print(f'- There are {len(no_dup)} that do not have duplicates') 
    ...: print(f'- All {len(nerscs)} are no longer in lfs/lustre/warehouse')
```

**Comment by ric-evans** [comment]
@jnbellinger @dsschult @blinkdog I'll follow up on what this means when I have a clear head

**Comment by ric-evans** [comment]
> I'm still puzzled. If we had a file in /data/..., even if we deleted it from the warehouse, so long as it exists in archive we want to keep the info around, right?

Sure, these are still around. Plenty. 

-----

In a similar but different scenario, if a file was 

 - in `/mnt/lfs*/...` and
 - it had no duplicate and
 - it is no longer in lfs/lustre/warehouse

Then, it was deleted regardless if it was at NERSC. (_This is why I'm confused about those 1008 above_)

**Comment by ric-evans** [comment]
If we wanted to preserve the FC entries that were at NERSC _and_ at `/mnt/lfs*/` but were deleted from lfs, then this is a problem. My understanding was that these were okay to delete.

**Comment by jnbellinger** [comment]
(name means directory name and file name together)

The end-state I thought we wanted is for every datafile to have a FC entry with its ideal name, and reference(s) to where it is.  If this is a Pole-data file that we don't want permanently in the warehouse (e.g. PFRaw), it should only have a NERSC reference--a bundle that contains it.  The name of that bundle should be an ideal name too.

When we want to look for the bundle at NERSC, we should be able to find it using its ideal name. (no /mnt/lfs7 stuff)

Working backwards, starting with bundles:
I "hsi mv" the bundles from their non-ideal names to their ideal names
FC references to those bundles have their names changed to reflect the ideal name.

If a (e.g.) PFRaw file has two entries:
 Do they point at the same bundle?
   If not, we have a problem demanding human inspection
   If yes, we delete whichever entry uses the non-ideal name
If a PFRaw file has one entry:
  If it does not have the ideal name, we change the name to the ideal name
If a PFRaw file has three or more entries, somebody needs to look at it

I have not done any replace-corrupt-copy_1-file-with-copy_2-file exercises, so at least we don't have to worry about that.

**Comment by dsschult** [comment]
> If we wanted to preserve the FC entries that were at NERSC _and_ at `/mnt/lfs*/` but were deleted from lfs, then this is a problem. My understanding was that these were okay to delete.

I think there was some miscommunication here.  We **_do_** want to keep these FC entries.  If they got deleted, that's not the end of the world.  Just makes recovery more difficult if we only want one file back, since we won't know which bundle it's in (unless that info was stored elsewhere).

**Comment by jnbellinger** [comment]
We could, at least in theory, retrieve them from backup too.  Though there's a 2-month horizon on the backup...

**Comment by ric-evans** [comment]
> I think there was some miscommunication here. We do want to keep these FC entries. If they got deleted, that's not the end of the world.

Yes, there most likely were FC entries that had a NERSC location that were deleted.

In the entire File Catalog there are 1679 entries left that have a `/mnt/` location _and_ a NERSC location. @jnbellinger go ahead and move the files over at NERSC so things look more consistent. If you get me a list of these files (and there are more than 1679 of them), then we can look into if we want to add-back anything to the File Catalog.

**Comment by jnbellinger** [comment]
There are only 130 bundles with the wrong name.
Shall I email you that info or stuff it here?

**Comment by ric-evans** [comment]
Is a bundle == an lfs directory?

Here is good

**Comment by jnbellinger** [comment]
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1123/13dbf46662d511ea93c442cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1114/fb8ff67062d411ea82d642cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1116/3d275a2e62d211eabd2d42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1117/4b2254f062d211ea82a942cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1117/0a3e6e1a62d511eab43842cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1012/cd8daf8c62d411ea96d942cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1021/ed4c9f2662d411eaa35842cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1021/5474306262d211eaa66942cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/0926/590d3dc862d211ea8dbf42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1022/f1dac76862d411eaae0742cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1022/f1e21ed262d411eaa01442cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1015/d85fa59e420811ea8c90c6259865d176.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1015/67065eda62d211ea84ed42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/0929/ef032a30421411ea8ca1c6259865d176.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/0929/6b54e5d262d211eab1bb42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/0928/7e15ff9c425811ea826bc6259865d176.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1017/e43881ca423711ea8beec6259865d176.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1017/7d85310662d211ea96eb42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1016/c11a5218425b11ea81d4c6259865d176.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1016/8f7cf15c62d211eab60042cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1016/dfc718c862d411eaae0e42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1008/c38ee602425f11eaad0bc6259865d176.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1113/d1ab2642427911eaa592c6259865d176.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1113/98960c9062d211ea8c0c42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1113/f6bc659c62d411ea847242cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1113/988f517462d211eaa18e42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1007/f877d6ac429a11eab9dcc6259865d176.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1013/32f728c042a111eaa38dea6d79d2daec.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1115/6cd9f64242a811eab8c6ea6d79d2daec.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1115/009cb79c62d511ea9f8042cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1004/0384bf3642bc11ea961eea6d79d2daec.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1004/fca9952c62d211ea9de242cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1004/fcaf9dcc62d211eab60742cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1004/b7ced1fe62d411eaa62d42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1001/4f8babda42bf11ea92e6ea6d79d2daec.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1005/3e8c218a42c511eaacadea6d79d2daec.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1005/bc43779462d411eab6f242cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1005/bc4990f662d411ea9a0042cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1006/62f93fae42c911eaac2cea6d79d2daec.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1006/0f0827cc62d311eaae6442cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1006/c079822662d411eaacb842cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1018/d7631ef647d311eab4028a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1018/ea0e979062d211ea9f7242cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1018/ee9b021c62d211ea8f0a42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1018/406dd00262d311ea8a6242cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1018/4073ee7862d311eaa68642cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1124/827ace5a62d211ea90af42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1124/8280c49862d211eabb6642cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1019/8ad847c262d211ea936542cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1019/8ad27c5c62d211eab2f142cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1003/b8bb4ef862d211ea8f4a42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1003/bd46f72862d211eabc8242cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1003/c653ab1062d211eab62942cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1003/d862f59062d211ea83a142cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1003/dceabbd262d211ea8b8142cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1003/c1d83d9a62d211eab37942cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1003/afde7be462d211eab19642cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1003/b44c81e862d211eabd0042cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1110/f81a3f1262d211eab0c842cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1110/4523a2a462d311ea8de042cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1110/f35cdb7662d211ea9a2742cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1122/2edc7c4262d311eaae0b42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1010/05c55c4062d311ea8d6542cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/0930/4e4e47da62d311ea9e7942cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/0925/f2a67ff688c611eabd66ea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1002/f6595d1a88c611eab34bea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1014/fe555f7488c611eaaa36ea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1014/fe4f345288c611ea982cea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1009/fa4f2fa288c611eabee9ea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1020/061114e488c711ea8711ea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1020/0616c06488c711eab7beea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1020/e8e1fb0262d411ea9ddc42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1011/01fd8c0c88c711ea8f02ea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1126/0a1f801888c711eaa88eea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1126/0a19e12688c711eab8feea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1123/6e67ebca42cd11ea86afea6d79d2daec.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1123/947cf8be62d411ea9d3742cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1114/6d3a49d8480c11eabeaf8a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1118/3615f5e4481111eaa0338a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1116/fdd67a58481511ea96f18a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1116/6712724062d311ea8a4e42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/0924/59ee2ce8481a11eaac308a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1117/39e7aecc482311eaa4be8a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1112/de5bdc00482711eaa7488a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1112/86e9a30862d311eab34142cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/0926/aca3a614483411eab8ca8a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1015/ae741a4c484611ea93538a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1015/beffb61862d311eaa0ad42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/0929/1ca44512484b11ea82268a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1014/a2ed1cec484f11eaa3768a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1109/6c4812d0485411ea9b548a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/0925/a4b5be7a485811ea86a18a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/0925/de456ab062d311ea934342cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1017/c8e6af52486111eaa17d8a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1017/edff62f662d311ea8d7c42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1124/9107330a486611eab71e8a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1124/f6720b6c62d311eabbc342cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/0928/0f7621c8488211eaa5b78a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/0928/fe3bf90662d311eab7b542cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1008/93a7cb3e48e411ea85f78a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1008/157907a862d411eab39e42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1113/9a7ca60c490911ea806d8a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1113/1de9d9b462d411ea9c6942cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1122/e8d790ac492711ea944a8a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1007/577cf388494d11eaacb78a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1007/2d507d7a62d411ea92dd42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1013/29116118496d11ea924a8a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1013/356cb1c262d411eab56342cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1115/156951a249a411eab5058a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1115/3e182d5c62d411ea894f42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1003/e61b1bc849d411eab8878a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1003/462c62f862d411eab23842cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1011/348000124a0d11eab83e8a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1011/4e1eb67e62d411eaa59f42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1002/efe06d5a4a4e11eaa4958a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1018/9ffbeaf64a9b11ea943e8a7b6d9b42de.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1018/5e12252262d411ea981242cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/0927/76541fc862d311eab41442cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1012/8edb913062d311eaad0942cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1022/a708655e62d311ea899142cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1111/b72d221262d311eabbdd42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1020/e654c3f662d311eaa9ee42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1004/6e50459062d411ea809142cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1001/762ad79462d411ea813842cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1010/7e078f8262d411eab84742cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1110/6651396462d411eaa91c42cd496541f0.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1021/109f02f688c711ea88a6ea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1009/16e5d62c88c711ea944fea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1016/245d629088c711eab5b9ea0bf4cac8d6.zip
/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFDST/1019/1d8e755e88c711eaa62eea0bf4cac8d6.zip

**Comment by ric-evans** [comment]
@jnbellinger thanks for the list. After these are mv'd at NERSC, there are three solutions I see to regenerate the deleted File Catalog entries, in decreasing difficulty:

A. Retrieve the files out of the archive, so we can fully re-index them.
B. Create bare minimum File Catalog entries with only WIPAC/NERSC `locations` (no checksums, event info, etc.)
C. Don't regenerate.

I like B. But it may break some downstream assumptions we have written.

@dsschult, @jnbellinger thoughts?

**Comment by dsschult** [comment]
I'd be good with B.

**Comment by ric-evans** [comment]
also @blinkdog what do you think? I see you've opened https://github.com/WIPACrepo/lta/issues/195

**Comment by jnbellinger** [comment]
Option D:
bsondump mongo-2_4/Month-2/2021-02-13/file_catalog/files.bson and retrieve the relevant info

**Comment by ric-evans** [comment]
I believe D is the ideal solution. The added benefit is I can search through this backup locally. And since @jnbellinger provided the bundle paths, these entries should be findable. 

I'd need to tweak the locations paths. Then POST to the FC.

**Comment by jnbellinger** [comment]
~jbellinger/Files.lfs7.json
It has 74200 lines, taken from the dump of files.bson, which have the string lfs7 in them.  Some of these are bundles, e.g. logical_name":"/home/projects/icecube/mnt/lfs7/exp/IceCube/2018/unbiased/PFRaw/1022/f1e21ed262d411eaa0144
2cd496541f0.zip, which contain a raft of /mnt/lfs7 files

**Comment by ric-evans** [comment]
thanks @jnbellinger this should be much easy now

**Comment by ric-evans** [comment]
Update: The deleted records have been restored. Working on the 671 duplicated records that were not deleted (bug in FC?).

**Comment by ric-evans** [comment]
> Update: The deleted records have been restored _now with /data/exp/ paths_. Working on the 671 duplicated records that were not deleted (bug in FC?).

This includes all bundles and regular file records

**Comment by ric-evans** [comment]
Remedied the remaining 671.

Finally, all is well in the FC. Not a single lfs path to be found.
